title: [ethoVR]
description: [Documentation for a Unity-based virtual reality system for neurobiology and ethology applications.]

remote_theme: pmarsceill/just-the-docs
#remote_theme: just-the-docs/just-the-docs
